# Use new container infrastructure to enable caching
sudo: false

# Do not choose a language; we provide our own build tools.
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
    - $HOME/.stack

# Ensure necessary system libraries are present
addons:
  apt:
    packages:
      - libgmp-dev

# Download and install the stack executable
before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local.bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

# Build dependencies
install:
  - stack --no-terminal --install-ghc test --only-dependencies

# Build the package, its tests, and its docs and run the tests
script:
  - stack --no-terminal test --haddock --no-haddock-deps
